POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Robert Romero",
    "number": "394-123-543-21"
}

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "",
    "number": "394-123-543-21"
}

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Adeline Markson",
    "number": ""
}